### ISSUE TITLE
Broken link to docs on encypting keys

### ISSUE THREAD

**Issue by jkunz** [adobe/reactor-developer-docs#1]
The link on https://docs.adobelaunch.com/launch-reference/publishing/adapters#sftp that points to instructions and Launch's public GPG keys points to https://developer.adobelaunch.com/guides/api/encrypting_values/ but should point to https://developer.adobelaunch.com/api/guides/encrypting_values/ .

**Comment by remear** [comment]
Moving this over to https://github.com/Adobe-Marketing-Cloud/reactor-user-docs, as it's an issue with the user-docs specifically.
