### ISSUE TITLE
Missing Extension Update page

### ISSUE THREAD

**Issue by thebenrob** [adobe/reactor-developer-docs#111]
# New topic request
 
## Description
 
There is no longer any page for extension update.  We have it referenced in a few places so, I think it used to exist: https://developer.adobelaunch.com/api/reference/1.0/extension_packages/update/

**Comment by remear** [comment]
This is noted in https://github.com/adobe/reactor-developer-docs/issues/19.

**Comment by thebenrob** [comment]
Closing as duplicate of #19
