### ISSUE TITLE
"Builds > List Builds for a Property" demos the wrong endpoint

### ISSUE THREAD

**Issue by perlmonger42** [adobe/reactor-developer-docs#12]
The DEFINTION, EXAMPLE REQUEST, and EXAMPLE RESPONSE are for `GET /libraries/:id/builds`.

The required scenario does not exist in `api_specfication.json`.

**Comment by spencerroan** [comment]
There is no `property.builds`.
There are `library.builds` and `environment.builds`.
This is a typo. 
I'll change `List Builds for a Property` to `List Builds for a Library`.

**Comment by spencerroan** [comment]
https://github.com/Adobe-Marketing-Cloud/reactor-developer-docs/pull/16
