### ISSUE TITLE
"Extensions > List revisions" demos the wrong endpoint

### ISSUE THREAD

**Issue by perlmonger42** [adobe/reactor-developer-docs#13]
The DEFINITION and EXAMPLE RESPONSE are for `GET /companies?filter[org_id]=EQ%203DB07B845A7DE2990A494126@AdobeOrg`.

The  EXAMPLE REQUEST seems to be `curl`-ing the right endpoint, though.

- `api/reference/1.0/extensions/revisions.md` references `extensions.list_the_revisions_of_an_extension`, and
- `api_specification.json` does contain that scenario, and
- that scenario does include an access to the right endpoint (`/extensions/:unrevised_extension_id/revisions`)
- but the wrong EXAMPLE RESPONSE data is being interpolated into `api/reference/1.0/extensions/revisions.md`

**Comment by spencerroan** [comment]
pr for this was merged.
