### ISSUE TITLE
"Rules > List revisions of a Rule" demos the wrong endpoint

### ISSUE THREAD

**Issue by perlmonger42** [adobe/reactor-developer-docs#14]
The DEFINITION and EXAMPLE RESPONSE are for `GET /companies?filter[org_id]=EQ%203DB07B845A7DE2990A494126@AdobeOrg`.

The  EXAMPLE REQUEST seems to be `curl`-ing the right endpoint, though.

**Comment by spencerroan** [comment]
I'm guessing there is a mismatch because we use a different token in the request.
`"/rules/:rule_id/revisions"` vs `"/rules/:origin_rule_id/revisions"`

**Comment by spencerroan** [comment]
same issue in https://github.com/Adobe-Marketing-Cloud/reactor-developer-docs/issues/13
data_elements has the same issue.

**Comment by spencerroan** [comment]
pr for this has merged.
