### ISSUE TITLE
Styling for code snippets in dark mode is almost invisible

### ISSUE THREAD

**Issue by thebenrob** [adobe/reactor-developer-docs#18]
`code` in dark mode is almost indistinguishable from the regular background color.

**Comment by remear** [comment]
Could you share a link to a page that demonstrates this?

**Comment by thebenrob** [comment]
I noticed it when doing the edits for the Breaking Changes page (https://developer.adobelaunch.com/api/release_notes/breaking-changes/)
![image](https://user-images.githubusercontent.com/31148336/56151569-bf2dc580-5f6e-11e9-83ad-e67f085eda63.png)

**Comment by remear** [comment]
Resolved by #29
