### ISSUE TITLE
Improve documentation with require elements for Create methods.  

### ISSUE THREAD

**Issue by pitchmuc** [adobe/reactor-developer-docs#41]
The create method documentation are listing the attributes that are required for the creation of rules, extension, etc... 
However, it may be require to add additional information some times (relationship for ruleComponent) and it is shown in example but not really clear why it is there and so on...

Could you please update the require element section on top of the example ? 
Thanks

**Comment by thebenrob** [comment]
@pitchmuc, if we take https://developer.adobelaunch.com/api/reference/1.0/rule_components/create/ as an example, are you wanting some basic description information that in addition to the attributes, you should also include relationships?  Or are you asking for some kind of expandable section (like the attributes) that describes relationships?

**Comment by pitchmuc** [comment]
@thebenrob It is assumed that you know what relationships mean and how to structure it. 
The approach that I follow and I recommend is to copy an existing structure but it doesn't exactly tell you what you are creating. 
It would be great that we have more explanation on each type of information fill in the body. 

An extended documentation on the attributes would be a great start.

**Comment by thebenrob** [comment]
We think this issue has been pretty well addressed with this new guide: https://developer.adobelaunch.com/api/guides/relationships/
