### ISSUE TITLE
DTM to be replaced by Launch ? 

### ISSUE THREAD

**Issue by pitchmuc** [adobe/reactor-developer-docs#42]
On the following page, it states that DTM will create the extension. 
I think you meant Launch. (in the Pending paragraph)

Page : https://developer.adobelaunch.com/api/reference/1.0/extensions/create/

Best,

**Comment by remear** [comment]
That's correct. Would you be interested in opening a pull request to get it fixed up?

**Comment by jasonwc** [comment]
Looks like this is no longer true, after doc changes. Thanks for submitting this issue!
