### ISSUE TITLE
Documentation on Filtering is incorrect and incomplete

### ISSUE THREAD

**Issue by stewartschillingsdi** [adobe/reactor-developer-docs#46]
https://developer.adobelaunch.com/api/guides/filtering/

This info is incorrect.  It does not mention the use of the "EQ" operator when defining a filter.  

I am told that there are other filter operators beyond just "EQ" but I do not know what they are. 

I also suggest that within the "Filters" panels of filterable API responses, that a link to the filtering usage be included.

**Comment by mems** [comment]
It looks like there also `GT`, `LT`, `LIKE`, `CONTAINS`, `NOT`, `STARTS WITH` (but "doesn't exist at the moment")

Note: You can use multiple values as `EQ foo, EQ bar, EQ some\,value\,with\,comma`.
Note 2: Some endpoint support additional filtering like extensions with param `max_availability` (not `filter[max_availability]`) with possible values `private`, `development` or `public`)

**Comment by stewartschillingsdi** [comment]
See also: https://github.com/adobe/reactor-developer-docs/issues/90
