### ISSUE TITLE
Property not supported by Audit Events

### ISSUE THREAD

**Issue by sagarsea** [adobe/reactor-developer-docs#76]
Hey Team,
When subscribing to Audit Events using Callbacks for properties , the API responds with error as detailed below. Our understanding was in reference to the audit events documentation here -  https://developer.adobelaunch.com/api/reference/1.0/audit_events/

{
  "errors": [
    {
      "id": "59d51d1d-212e-4ef3-8930-96cc93c8415d",
      "status": "400",
      "code": "schema-validation-error",
      "title": "Schema Validation Error",
      "detail": "The property 'data/attributes/subscriptions/0' value \"property.created\" did not match the pattern '^(host|build|callback|data_element|environment|extension|library|rule|rule_component)\\.(created|updated|deleted)$'",
      "meta": {},
      "source": {}
    },
    {
      "id": "7b8169f3-360f-46ac-8b4d-3837d91c71f7",
      "status": "400",
      "code": "schema-validation-error",
      "title": "Schema Validation Error",
      "detail": "The property 'data/attributes/subscriptions/9' value \"property.updated\" did not match the pattern '^(host|build|callback|data_element|environment|extension|library|rule|rule_component)\\.(created|updated|deleted)$'",
      "meta": {},
      "source": {}
    },
    {
      "id": "955a5ef3-27b7-4cd8-9264-9ceb0295adad",
      "status": "400",
      "code": "schema-validation-error",
      "title": "Schema Validation Error",
      "detail": "The property 'data/attributes/subscriptions/18' value \"property.deleted\" did not match the pattern '^(host|build|callback|data_element|environment|extension|library|rule|rule_component)\\.(created|updated|deleted)$'",
      "meta": {},
      "source": {}
    }
  ]
}

[PostMan-Request.txt](https://github.com/adobe/reactor-developer-docs/files/4467533/PostMan-Request.txt)

**Comment by thebenrob** [comment]
The API does support callbacks on the property resource.  Callbacks exist within the context of a property, meaning you cannot create them until after the property exists.  Thus, it would be impossible to ever generate a callback for property.created.  Also, when a property is deleted, all its callbacks are also deleted through a cascade, so the callback definition is gone and it would be impossible to get a callback for property.deleted.  Given this, we determined not to implement callbacks for property.updated for consistency.  We'll update the docs to reflect that you cannot create callbacks for the property resource.
